# Generated by Django 5.0.1 on 2024-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('jira_id', models.CharField(blank=True, max_length=100)),
                ('request_json', models.TextField(blank=True)),
                ('result_json', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
