# Generated by Django 5.0.1 on 2024-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        ('test_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='test_cases',
            field=models.ManyToManyField(blank=True, to='test_utils.testcase'),
        ),
    ]
